### ISSUE TITLE
Problems installing oidc-agent for RHEL users.

### ISSUE THREAD

**Issue by paulmillar** [indigo-dc/oidc-agent#350]
The oidc-agent documentation's [install page](https://indigo-dc.gitbook.io/oidc-agent/installation/install) describes various install options:

There are a number of problems:
1. The `repo.data.kit.edu` repo does not contain RHEL packages,
2. The GitHub contains RHEL v7 packages (only this version), but they are not organised as a repo,
3. The `repo.indigo-datacloud.eu` repo no longer works.

In combination, this means there are currently no good ways to install oidc-agent for RHEL users.

**Comment by marcvs** [comment]
I'm progressing with my builds for various linux distributions. (And getting really mad about redhat/rpm).
Is there any docker container you'd suggest for builds with RHEL v7?
I tried `registry.access.redhat.com/ubi8/ubi:8.1` but that one does not seem to be able to install epel and remi repositories (which contain required packages)

**Comment by paulmillar** [comment]
Sorry, I don't have much experience with building RHEL.  For dCache, we build on native platforms (via OpenStack).  Our builds are handled by Jenkins.  It kinda works, but I'm not sure this is the best tool for building packages on multiple platforms.

**Comment by marcvs** [comment]
I have uploaded **FRESHLY** the current oidc-agent packages for `centos[78]` to repo.data.kit.edu. 
They have a better dependency handling, but they are still undergoing some changes regarding the rpm packaging.
I.e. your feedback will be higly appreciated, but changes will come.  
The code of oidc-agent and its functionality is not being touched by this.

Could you confirm that the repository works for RHEL?

**Comment by paulmillar** [comment]
Thanks @marcvs.

The repo seems not to be working right now on my test CentOS 7 machine:

```console
[root@paul-oidc-agent ~]# cat /etc/yum.repos.d/data-kit-edu-centos7.repo 
[repo-data-kit-edu]
name=repo-data.kit.edu
baseurl=https://repo.data.kit.edu/centos/centos7
gpgcheck=1
enabled=1
gpgkey=https://repo.data.kit.edu/repo-data-kit-edu-key.gpg
[root@paul-oidc-agent ~]# yum install oidc-agent
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.agdsn.de
 * epel: mirror.netzwerge.de
 * extras: ftp.tu-chemnitz.de
 * updates: ftp.rrzn.uni-hannover.de
No package oidc-agent available.
Error: Nothing to do
[root@paul-oidc-agent ~]# 
```

**Comment by marcvs** [comment]
Oops; my bad. I fixed it.
Please note: If it's a centos7, then it's probably not a desktop  :)
That is what we addressed with splitting the packages:
 - `oidc-agent` => `oidc-agent-cli` + `oidc-agent-desktop`
You're probably best off with only the cli, also because we depend on `yad`, which pulls all kind of useless dependencies (such as `cdparanoia-libs`, and `ModemManager-glib` :facepalm:

**Comment by paulmillar** [comment]
Thanks for the hint.  Indeed the CentOS machines are not desktops, so just `oidc-agent-cli` should be sufficient.

Unfortunately, the repo still doesn't seem to be working for me: yum cannot find either `oidc-agent` or `oidc-agent-cli`:

```console
[root@paul-oidc-agent centos]# yum install oidc-agent
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.agdsn.de
 * epel: fedora.tu-chemnitz.de
 * extras: ftp.tu-chemnitz.de
 * updates: ftp.rrzn.uni-hannover.de
No package oidc-agent available.
Error: Nothing to do
[root@paul-oidc-agent centos]# yum install oidc-agent-cli
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.agdsn.de
 * epel: mirror.netzwerge.de
 * extras: ftp.tu-chemnitz.de
 * updates: ftp.rrzn.uni-hannover.de
No package oidc-agent-cli available.
Error: Nothing to do
[root@paul-oidc-agent centos]# 
```

**Comment by marcvs** [comment]
Hmm, it works on my centos7 and our yum repo config is identical. 
Could you try again with running `yum clean expire-cache` first?

**Comment by marcvs** [comment]
Ah, and I found it to be a good idea to disable `fastestmirror` by setting `enable=0` in `/etc/yum/pluginconf.d/fastestmirror.conf` in an unrelated case.

**Comment by paulmillar** [comment]
Yes, with `yum clean expire-cache` the packages were downloaded correctly and installed.

Thanks for your help @marcvs !
